
services:
  db:
    image:  postgres:18.3-alpine3.22
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../pg/conf/custom_pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf:ro
      - ../pg/conf/custom_postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro
      - ../pg/sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    command: ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p ${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rust-collector:
    ports:
      - "7081:8080"
    user: "1001:1001"
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile.hardened
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  pgdata: