# TYPE  DATABASE            USER                 ADDRESS                 METHOD
host    ttn_dust_sensors    ttn_user             192.168.0.0/16          md5
host    ttn_dust_sensors    ttn_dust_sensors     192.168.0.0/16          md5
