name: Rust CI

on:
  push:
    paths:
      - 'rust-collector/**'
  pull_request:
    paths:
      - 'rust-collector/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        run: cargo build --release
        working-directory: rust-collector

      - name: Test
        run: cargo test --all --release
        working-directory: rust-collector
